### ISSUE TITLE
Sidebar centered on page within current Firefox version

### ISSUE THREAD

**Issue by yukon-cornelius** [SteamDatabase/SteamDatabase#418] opened 2015-12-19 07:26 UTC
The sidebar that appears on game pages is currently centered on page for the most current Firefox version (42.0) where debugger says "div.tabnav" is statically positioned from the top of size 940x73.6.  Doesn't repro in IE or Chrome, where debugger says "div.tabnav" is sized 149x304, with offsets of 521 down & 119 left, and a left margin of -171.  See screenshot for example.
![steamdb_sidebar](https://cloud.githubusercontent.com/assets/6321786/11912004/b700489e-a5de-11e5-85c5-174cd9a4fc7d.jpg)

**Comment by johndrinkwater** [comment] 2015-12-19 10:02
Cannot reproduce here (though I am on 43), what extensions are you running? What’s the window size? If you clear cache, does that fix it?

**Comment by xPaw** [comment] 2015-12-24 14:19
I can't reproduce this either. Do you have more details?

**Comment by SuperStream** [comment] 2015-12-26 18:32
Same thing here 

Win 8.1 x64 // Firefox 43.0.2

http://imgur.com/BFYkcgi

**Comment by xPaw** [comment] 2015-12-26 19:31
This might be a problem with firefox not calculating sub pixel positions correctly.

**Comment by kmg90** [comment] 2016-01-01 13:23
I don't have a system to check (Mac) but it appears the issue only shows in up in the Windows version of Firefox (and forks) as the navtab is properly positioned on Fedora 23 but not on Win 7 machine with Firefox 44b4 
![screenshot at 2016-01-01 07 10 15](https://cloud.githubusercontent.com/assets/4296643/12070946/68088804-b057-11e5-9413-9881b827a074.png)

**Comment by yukon-cornelius** [comment] 2016-01-22 00:43
Still repro'd on 43.0.4 ... note that when I launch FF's native Inspector docked to the right-1/3 of the window, the positioning of the 'nav.tabnav-tabs' locates 'Prices' at an absolute position off-center, then includes additional navbar off to the right, where it wraps back again at the left-border.  I've also noticed the location of 'Prices' is absolutely fixed, and doesn't shift or auto-center as I reduce the window width, so I'm guessing there's a dependency upon the 940px minimum width that computes incorrectly when either page-zoom isn't 100%, or when the display width is less than 940.
![inspector-docked-right](https://cloud.githubusercontent.com/assets/6321786/12499170/03cfb086-c05d-11e5-837a-6bc0c79a94d2.jpg)

**Comment by yukon-cornelius** [comment] 2016-01-22 00:56
OK, here's the scoop on window widths ...
* When the window width is <=1280, then 'nav.tabnav-tabs' displays positioned off-center & consumes 940px wide, and doesn't display icons next to each word.
* When the window width is 1282, then 'nav.tabnav-tabs' still consumes 940px, but then icons display next to words.
* When the window width is >=1284, then 'nav.tabnav-tabs' sizes to the vertical orientation, but horizontal positioning is messed up.
See attached for screenshots of window @ 1282px and 1284px.
![window 1282 width](https://cloud.githubusercontent.com/assets/6321786/12499435/68b53c8a-c05f-11e5-9a74-704785afa185.jpg)
![window 1284 width](https://cloud.githubusercontent.com/assets/6321786/12499483/da09c16c-c05f-11e5-864e-68f125a96cdb.jpg)

**Comment by xPaw** [comment] 2016-01-22 09:06
There are only two media queries that are related to the tab bar:

- `@media (min-width: 1300px)` - Moves it to the side and makes it vertical
- `@media (max-width: 1299px)` - Hides icons

There's nothing more to that, And looking at your screenshots, it really does look like a Firefox bug, there aren't even any styles that would cause default tab bar to be rendered with absolute positioning.

**Comment by xPaw** [comment] 2016-06-06 17:39
Is this still a thing that happens or was it fixed?

**Comment by xPaw** [comment] 2016-06-15 19:47
Okay I figured it out, it seems to be an entirely firefox bug.

This was caused by:
```css
.tabbable {
	margin-top: -1px;
}
```

fixed by:
```css
.tabbable {
	top: -1px;
	position: relative;
}
```

**Closed by xPaw** 2016-06-15 19:47 UTC
Labels: Bug, Website
